### ISSUE TITLE
[PimcoreBundle] Undefined class constant 'VERSIONS'

### ISSUE THREAD

**Issue by danmichaelo** [coreshop/CoreShop#1546]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When visiting Pimcore's Bundle Manager Admin GUI (`/admin/extensionmanager/admin/extensions`), I get

```
Status: 500 | Internal Server Error
URL: /admin/extensionmanager/admin/extensions?_dc=1608218384287
Method: GET
Message: Undefined class constant 'VERSIONS'
Trace: 
in /var/www/html/vendor/coreshop/pimcore-bundle/CoreShopPimcoreBundle.php:52
#0 /var/www/html/vendor/pimcore/pimcore/lib/Extension/Bundle/Traits/PackageVersionTrait.php(39): CoreShop\Bundle\PimcoreBundle\CoreShopPimcoreBundle->getComposerPackageName()
#1 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php(401): CoreShop\Bundle\PimcoreBundle\CoreShopPimcoreBundle->getVersion()
#2 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php(319): Pimcore\Bundle\AdminBundle\Controller\ExtensionManager\ExtensionManagerController->buildBundleInfo(Object(CoreShop\Bundle\PimcoreBundle\CoreShopPimcoreBundle))
#3 /var/www/html/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/ExtensionManager/ExtensionManagerController.php(82): Pimcore\Bundle\AdminBundle\Controller\ExtensionManager\ExtensionManagerController->getBundleList()
#4 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(158): Pimcore\Bundle\AdminBundle\Controller\ExtensionManager\ExtensionManagerController->getExtensionsAction()
#5 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#6 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#7 /var/www/html/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#8 {main}
```

It seems like the `VERSIONS` constant was removed in https://github.com/Ocramius/PackageVersions/commit/3f81724a2369c3c83d0db99097b09c81c0dec8a0 , but it seems like there is a new static `getVersion()` method on the same class.

**Comment by solverat** [comment]
This has been fixed already on latest 2.x (https://github.com/coreshop/CoreShop/commit/ef1814c7aee56df14b8bec75c1b055b7bd095057)

**Comment by danmichaelo** [comment]
Ah, it's just not released yet! Thanks, @solverat !
