### ISSUE TITLE
Wild error message when using Order messages with no sales contact defined

### ISSUE THREAD

**Issue by JulienHenchoz** [coreshop/CoreShop#169]
Steps to reproduce the issue : 

1. Make sure no "Sales contact" are defined in the CoreShop settings
2. Create an order
3. In the order backend module, type a message in the "Messages" section on the right and hit "Send"
4. A wild error message appears  : 

```
Ext.JSON.decode(): You're trying to decode an invalid JSON String: 
Fatal error: Uncaught Error: Call to a member function getId() on null in /home/pimcore/plugins/CoreShop/controllers/Admin/OrderController.php:367 
Stack trace: 
#0 /home/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): CoreShop_Admin_OrderController->sendMessageAction() 
#1 /home/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('sendMessageActi...') 
#2 /home/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) 
#3 /home/pimcore/pimcore/lib/Pimcore.php(152): Zend_Controller_Front->dispatch(Object(Ze in /home/pimcore/plugins/CoreShop/controllers/Admin/OrderController.php on line 367
```

This can be a bit confusing for a non technical user.

**Comment by JulienHenchoz** [comment]
Another message of the same type appears when : 

1. A sales contact is set
2. No thread states exist
3. You send a first message through the order interface
4. Try sending a second one, and you get : 

```
Fatal error: Uncaught Error: Call to a member function getFinished() on null in /home/pimcore/plugins/CoreShop/lib/CoreShop/Model/Messaging/Thread.php:144 Stack trace: 
#0 /home/pimcore/plugins/CoreShop/controllers/Admin/OrderController.php(367): CoreShop\Model\Messaging\Thread::searchThread('jhenchoz@cobweb...', '1', '2', '6291') 
#1 /home/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): CoreShop_Admin_OrderController->sendMessageAction() 
#2 /home/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('sendMessageActi...') 
#3 /home/pimcore/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->di in /home/pimcore/plugins/CoreShop/lib/CoreShop/Model/Messaging/Thread.php on line 144


```

**Comment by dpfaffenbauer** [comment]
fixed
