### ISSUE TITLE
CustomerGroup (should now be UserGroup?) by default has a options provider which doesn't exist

### ISSUE THREAD

**Issue by dkarlovi** [coreshop/CoreShop#1771]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

```diff
-CoreShop\\Bundle\\CustomerBundle\\CoreExtension\\Provider\\RoleOptionsProvider
+CoreShop\\Bundle\\UserBundle\\CoreExtension\\Provider\\RoleOptionsProvider
```

BTW in #665 customer and user were split in two. `CustomerGroup` should now probably be `UserGroup`?

**Comment by jdreesen** [comment]
This is currently broken in `v3.0.0-beta.1`.



```sh
> bin/console pimcore:deployment:classes-rebuild
ERROR [pimcore] Error: Class "CoreShop\Bundle\CustomerBundle\CoreExtension\Provider\RoleOptionsProvider" not found in /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Helper/ClassResolver.php:39
Stack trace:
#0 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Helper/OptionsProviderResolver.php(37): Pimcore\Model\DataObject\ClassDefinition\Helper\ClassResolver::resolve('CoreShop\\Bundle...', Object(Closure))
#1 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Multiselect.php(656): Pimcore\Model\DataObject\ClassDefinition\Helper\OptionsProviderResolver::resolveProvider('CoreShop\\Bundle...', 2)
#2 /var/www/html/vendor/pimcore/pimcore/models/DataObject/ClassDefinition.php(413): Pimcore\Model\DataObject\ClassDefinition\Data\Multiselect->preSave(Object(Pimcore\Model\DataObject\ClassDefinition))
#3 /var/www/html/vendor/pimcore/pimcore/bundles/CoreBundle/Command/ClassesRebuildCommand.php(117): Pimcore\Model\DataObject\ClassDefinition->save(false)
#4 /var/www/html/vendor/symfony/console/Command/Command.php(299): Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/vendor/symfony/console/Application.php(996): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/vendor/symfony/console/Application.php(295): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Pimcore\Bundle\CoreBundle\Command\ClassesRebuildCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/symfony/console/Application.php(167): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/bin/console(49): Symfony\Component\Console\Application->run()
#11 {main}
```

**Comment by dpfaffenbauer** [comment]
"broken" -> it gives an error but still works :P. I am on that already
