### ISSUE TITLE
adding/editig product filters - Error is raised

### ISSUE THREAD

**Issue by JustMe69** [coreshop/CoreShop#1921]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

using CoreShop 3 - dev-master

When editing or adding product-filter error below is shown

![grafik](https://user-images.githubusercontent.com/23456403/159430926-8ba12900-ab10-4264-bd53-05e8dae129e6.png)

with details:
```
Timestamp: Tue Mar 22 2022 08:37:20 GMT+0100 (Mitteleuropäische Normalzeit)
Status: 500 | Internal Server Error
URL: /admin/coreshop/filters/get-values-for-filter-field?_dc=1647934637924
Method: GET
Message: explode(): Argument #2 ($string) must be of type string, null given
Trace: 
in /var/www/dev/vendor/coreshop/core-shop/src/CoreShop/Component/Index/Worker/FilterGroupHelper.php:71
#0 /var/www/dev/vendor/coreshop/core-shop/src/CoreShop/Component/Index/Worker/FilterGroupHelper.php(71): explode()
#1 /var/www/dev/vendor/coreshop/core-shop/src/CoreShop/Bundle/IndexBundle/Controller/FilterController.php(81): CoreShop\Component\Index\Worker\FilterGroupHelper->getGroupByValuesForFilterGroup()
#2 /var/www/dev/vendor/symfony/http-kernel/HttpKernel.php(152): CoreShop\Bundle\IndexBundle\Controller\FilterController->getValuesForFilterFieldAction()
#3 /var/www/dev/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#4 /var/www/dev/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle()
#5 /var/www/dev/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle()
#6 {main}
```

working on filters is still possible after clicking message away.

**Comment by dpfaffenbauer** [comment]
Does the select value have values? This is too little information to further proceed. Please provide more information
