### ISSUE TITLE
CoreShopProduct - Product Price Rules - Condition removal error

### ISSUE THREAD

**Issue by IvanJavorovic** [coreshop/CoreShop#2085]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

After adding a new Product Price Rule on a single CoreShopProduct object saving the object, then deleting the Condition within the Product Price Rule and clicking save and publish the following error occurs:
```
Timestamp: Mon Sep 26 2022 13:01:35 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/object/save?task=publish
Method: PUT
Message: Given object is not an instance of the class this property was declared in
Trace: 
in /var/www/html/vendor/coreshop/core-shop/src/CoreShop/Bundle/ResourceBundle/Doctrine/ORM/EntityMerger.php:112
#0 /var/www/html/vendor/coreshop/core-shop/src/CoreShop/Bundle/ResourceBundle/Doctrine/ORM/EntityMerger.php(112): ReflectionProperty->getValue(Object(CoreShop\Component\Rule\Model\Condition))
#1 /var/www/html/vendor/coreshop/core-shop/src/CoreShop/Bundle/ResourceBundle/Doctrine/ORM/EntityMerger.php(90): CoreShop\Bundle\ResourceBundle\Doctrine\ORM\EntityMerger->checkAssociations(Object(CoreShop\Component\Product\Model\ProductSpecificPriceRule), Object(CoreShop\Component\Rule\Model\Condition), Array)
#2 /var/www/html/vendor/coreshop/core-shop/src/CoreShop/Bundle/ResourceBundle/Doctrine/ORM/EntityMerger.php(43): CoreShop\Bundle\ResourceBundle\Doctrine\ORM\EntityMerger->doMerge(Object(CoreShop\Component\Product\Model\ProductSpecificPriceRule), Array)
#3 /var/www/html/vendor/coreshop/core-shop/src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php(382): CoreShop\Bundle\ResourceBundle\Doctrine\ORM\EntityMerger->merge(Object(CoreShop\Component\Product\Model\ProductSpecificPriceRule))
#4 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Concrete/Dao.php(262): CoreShop\Bundle\ProductBundle\CoreExtension\ProductSpecificPriceRules->save(Object(Pimcore\Model\DataObject\CoreShopProduct), Array)
#5 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Concrete.php(199): Pimcore\Model\DataObject\Concrete\Dao->update(true)
#6 /var/www/html/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php(735): Pimcore\Model\DataObject\Concrete->update(true, Array)
#7 /var/www/html/vendor/pimcore/pimcore/models/DataObject/Concrete.php(711): Pimcore\Model\DataObject\AbstractObject->save(Array)
#8 /var/www/html/src/Override/DataObjectControllerOverride.php(1362): Pimcore\Model\DataObject\Concrete->save()
#9 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(152): App\Override\DataObjectControllerOverride->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#10 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /var/www/html/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/www/html/public/index.php(69): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
```

**Comment by dkarlovi** [comment]
@IvanJavorovic can you retest with 3.0.2? There was some fixes related to price conditions.

**Comment by dpfaffenbauer** [comment]
cannot be reproduced anymore.
