### ISSUE TITLE
 Call to a member function getUser() on null

### ISSUE THREAD

**Issue by ITspirit** [coreshop/CoreShop#2225]
Pimcore 10.6-dev Installation with w-vison/data-definition bundle.

```
URL: /admin/data_definitions/import_definitions/get
Message: Call to a member function getUser() on null
Trace: 
in /app/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/AdminController.php:159
#0 /app/vendor/coreshop/resource-bundle/Controller/ResourceController.php(63): Pimcore\Bundle\AdminBundle\Controller\AdminController->getAdminUser()
#1 /app/vendor/coreshop/resource-bundle/Controller/ResourceController.php(82): CoreShop\Bundle\ResourceBundle\Controller\ResourceController->isGrantedOr403()
#2 /app/vendor/symfony/http-kernel/HttpKernel.php(163): CoreShop\Bundle\ResourceBundle\Controller\ResourceController->getAction(Object(Symfony\Component\HttpFoundation\Request))
#3 /app/vendor/symfony/http-kernel/HttpKernel.php(75): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#4 /app/vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#5 /app/public/index.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#6 {main}
```

Bundle is installable.
Defined/Existing Import/Exports are shown and will be executed

But modify isn´t possible, will show up this error above.

Ticket created as requested in gitter.

Maybe an Issue with Security/TokeResolver/DI?

**Comment by dpfaffenbauer** [comment]
@ITspirit is this still a problem? we use data-def every day and I think that this is solved already
