### ISSUE TITLE
Error saving Store changes in translated admin

### ISSUE THREAD

**Issue by kmpm** [coreshop/CoreShop#940]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

When running the admin in a translated (Swedish) environment and editing a store I get an error saving.
This is probably related to #937
```
Timestamp: Wed Apr 10 2019 12:26:18 GMT+0200 (centraleuropeisk sommartid)
Status: 500 | Internal Server Error
URL: /admin/coreshop/stores/save
Method: post
Message: An exception occurred while executing 'INSERT INTO coreshop_country_translation (name, creationDate, modificationDate, locale, translatable_id) VALUES (?, ?, ?, ?, ?)' with params [null, "2019-04-10", "2019-04-10 12:26:18", "sv", 16]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null
Trace: 
#0 /projects/coreshop/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(169): Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /projects/coreshop/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(145): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'An exception oc...')
#2 /projects/coreshop/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(162): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO cor...', Array)
#3 /projects/coreshop/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(285): Doctrine\DBAL\Statement->execute()
#4 /projects/coreshop/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1073): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
#5 /projects/coreshop/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(386): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
#6 /projects/coreshop/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(359): Doctrine\ORM\UnitOfWork->commit(NULL)
#7 /projects/coreshop/var/cache/dev/ContainerQ9hglj1/EntityManager_9a5be93.php(125): Doctrine\ORM\EntityManager->flush(NULL)
#8 /home/sysadmin/core-shop/src/CoreShop/Bundle/ResourceBundle/Controller/ResourceController.php(162): EntityManager_9a5be93->flush()
#9 /projects/coreshop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): CoreShop\Bundle\ResourceBundle\Controller\ResourceController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#10 /projects/coreshop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /projects/coreshop/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /projects/coreshop/web/app.php(42): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
```

![image](https://user-images.githubusercontent.com/96618/55871989-27a22e80-5b8c-11e9-8aac-89208be2fa24.png)

**Comment by dpfaffenbauer** [comment]
just had the same issue... not sure why this happens, but I will look into it.
