### ISSUE TITLE
Cannot create Product Specific Price Rule

### ISSUE THREAD

**Issue by solverat** [coreshop/CoreShop#952]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

![image](https://user-images.githubusercontent.com/700119/56365149-74bb7b80-61f0-11e9-9a46-f3bf40e6c59c.png)

On save:

```bash
Message: Call to a member function containsKey() on null

Trace: 
#0 /var/www/public/vendor/coreshop/core-shop/src/CoreShop/Component/Resource/Model/TranslatableTrait.php(118): CoreShop\Component\Product\Model\AbstractPriceRule->hasTranslation(Object(CoreShop\Component\Product\Model\ProductSpecificPriceRuleTranslation))
#1 /var/www/public/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php(674): CoreShop\Component\Product\Model\AbstractPriceRule->addTranslation(Object(CoreShop\Component\Product\Model\ProductSpecificPriceRuleTranslation))
#2 /var/www/public/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php(622): Symfony\Component\PropertyAccess\PropertyAccessor->writeCollection(Array, 'translations', Array, 'addTranslation', 'removeTranslati...')
#3 /var/www/public/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php(216): Symfony\Component\PropertyAccess\PropertyAccessor->writeProperty(Array, 'translations', Array)
#4 /var/www/public/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php(86): Symfony\Component\PropertyAccess\PropertyAccessor->setValue(Object(CoreShop\Component\Product\Model\ProductSpecificPriceRule), Object(Symfony\Component\PropertyAccess\PropertyPath), Array)
#5 /var/www/public/vendor/symfony/symfony/src/Symfony/Component/Form/Form.php(636): Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapFormsToData(Object(RecursiveIteratorIterator), Object(CoreShop\Component\Product\Model\ProductSpecificPriceRule))
#6 /var/www/public/vendor/coreshop/core-shop/src/CoreShop/Bundle/ProductBundle/CoreExtension/ProductSpecificPriceRules.php(192): Symfony\Component\Form\Form->submit(Array)
#7 /var/www/public/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php(1211): CoreShop\Bundle\ProductBundle\CoreExtension\ProductSpecificPriceRules->getDataFromEditmode(Array, Object(Pimcore\Model\DataObject\CoreShopProduct))
#8 /var/www/public/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->saveAction(Object(Symfony\Component\HttpFoundation\Request))
#9 /var/www/public/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /var/www/public/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(200): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/www/public/web/app.php(42): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#12 {main}
```

**Comment by dpfaffenbauer** [comment]
fixed
